In [56]:
import numpy as np
import pandas as pd

In [57]:
import sys
print(sys.executable)

c:\Users\chava\AppData\Local\Programs\Python\Python313\python.exe


In [58]:
array=[1,38,67,5,98]
arr = np.array(array)
print(arr)
hi = np.linspace(1,8,num =4,dtype= int)
print(hi)



[ 1 38 67  5 98]
[1 3 5 8]


In [59]:
print(hi[:2])
new_arr= arr[1:].copy()
new_arr[2]=90
print(arr)
print(new_arr)

[1 3]
[ 1 38 67  5 98]
[38 67 90 98]


In [60]:
arr3D = np.array([[[1,8],[33,55],[6,9]],[[45,7],[89,54],[89,78]]])
print(arr3D)
arr3D_d=arr3D.reshape(6,2)
print(arr3D_d)

[[[ 1  8]
  [33 55]
  [ 6  9]]

 [[45  7]
  [89 54]
  [89 78]]]
[[ 1  8]
 [33 55]
 [ 6  9]
 [45  7]
 [89 54]
 [89 78]]


In [61]:
print(hi ** 2)

[ 1  9 25 64]


In [62]:
%pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [63]:
import openpyxl 

In [64]:
df = pd.read_excel(r"C:\Users\chava\Downloads\MOCK_DATA (1).xlsx")
df.sample(5)

,Student Roll no.,first_name,last_name,email,Department,CGPA,Resume link
27,28,Moyna,Raeburn,mraeburnr@hugedomains.com,INFT,8.85,https://oakley.com/lobortis.aspx?sed=feugiat&t...
20,21,Marcela,Croser,mcroserk@edublogs.org,ELEC,9.01,https://nationalgeographic.com/ut/at/dolor/qui...
24,25,Druci,Thrift,dthrifto@mapquest.com,INFT,8.51,https://macromedia.com/sapien/a/libero/nam/dui...
31,32,Godart,Fridlington,gfridlingtonv@indiegogo.com,ELEC,7.53,http://mapy.cz/accumsan/odio/curabitur/convall...
4,5,Uri,Copestake,ucopestake4@dailymail.co.uk,ELEC,9.00,https://cargocollective.com/luctus/tincidunt/n...


In [65]:
# resume_links = df["Resume link"].to_list()
# df.drop(columns=["Resume link"],inplace=True)

In [66]:
df.drop_duplicates(subset=["email","first_name","last_name"])

,Student Roll no.,first_name,last_name,email,Department,CGPA,Resume link
0,1,Gertie,Blaske,gblaske0@imdb.com,ELEC,8.63,http://cdc.gov/erat.png?integer=urna&ac=ut&neq...
1,2,Dall,Edgin,dedgin1@un.org,CMPN,8.67,https://kickstarter.com/mattis/egestas.html?nu...
2,3,Conny,Peppard,cpeppard2@360.cn,ELEC,7.85,https://ning.com/nullam/porttitor/lacus/at/tur...
3,4,Karry,Stille,kstille3@sun.com,ELEC,9.34,http://seattletimes.com/quis.js?urna=at&ut=vel...
4,5,Uri,Copestake,ucopestake4@dailymail.co.uk,ELEC,9.00,https://cargocollective.com/luctus/tincidunt/n...
5,6,Bev,Jerdan,bjerdan5@comsenz.com,ELEC,8.54,http://washington.edu/erat.xml?vitae=lacinia&c...
6,7,Kelly,Fergyson,kfergyson6@bing.com,ECS,8.89,https://google.ca/diam/erat/fermentum/justo.js...
7,8,Josefa,Delion,jdelion7@wix.com,ELEC,8.25,https://berkeley.edu/non/mi/integer/ac/neque/d...
8,9,Avivah,Botger,abotger8@dropbox.com,ECS,8.24,https://webnode.com/enim/leo/rhoncus/sed.jsp?e...
9,10,Pauli,Probyn,pprobyn9@bravesites.com,INFT,8.08,http://infoseek.co.jp/viverra/pede/ac.xml?maec...


In [67]:
# idx = df.groupby(["first_name","last_name"])["CGPA"].idxmax()
# print(idx)
# cleaned_df = df.loc[idx].sort_values(by="CGPA",ascending=False)

In [68]:
cleaned_df=df[df["CGPA"]>=9.0]
print(cleaned_df)

    Student Roll no. first_name  last_name                        email  \
3                  4      Karry     Stille             kstille3@sun.com   
4                  5        Uri  Copestake  ucopestake4@dailymail.co.uk   
18                19       Leia   McGeachy      lmcgeachyi@redcross.org   
19                20     Gibbie    Rattrie          grattriej@bbc.co.uk   
20                21    Marcela     Croser        mcroserk@edublogs.org   
22                23     Dionne    Rearden       dreardenm@multiply.com   
23                24       Arny     Vogele     avogelen@themeforest.net   

   Department  CGPA                                        Resume link  
3        ELEC  9.34  http://seattletimes.com/quis.js?urna=at&ut=vel...  
4        ELEC  9.00  https://cargocollective.com/luctus/tincidunt/n...  
18        ECS  9.81  http://patch.com/eget/nunc/donec.aspx?nunc=tem...  
19        ECS  9.90  http://instagram.com/turpis/donec.jsp?dui=volu...  
20       ELEC  9.01  https://natio

In [69]:
df["CGPA"].astype(int)
cleaned_df = df[(df["CGPA"]>=8.5)&((df["Department"]=="CMPN") | (df["Department"]=="INFT"))]
cleaned_df=cleaned_df.sort_values("CGPA",ascending=False)
print(cleaned_df)

    Student Roll no. first_name last_name                      email  \
23                24       Arny    Vogele   avogelen@themeforest.net   
22                23     Dionne   Rearden     dreardenm@multiply.com   
14                15    Shelagh   Drayson        sdraysone@ifeng.com   
15                16       Mark   Sharpus        msharpusf@ocn.ne.jp   
27                28      Moyna   Raeburn  mraeburnr@hugedomains.com   
1                  2       Dall     Edgin             dedgin1@un.org   
24                25      Druci    Thrift      dthrifto@mapquest.com   

   Department  CGPA                                        Resume link  
23       INFT  9.81  http://ifeng.com/convallis.json?etiam=dolor&pr...  
22       INFT  9.58  http://wikia.com/aliquet/pulvinar/sed/nisl.jso...  
14       INFT  8.99  https://youtu.be/fusce.png?maecenas=habitasse&...  
15       INFT  8.99  http://theguardian.com/nisi/venenatis/tristiqu...  
27       INFT  8.85  https://oakley.com/lobortis.aspx?sed=

In [70]:
# print(resume_links)
resume_links=df.groupby("first_name")["Resume link"].apply(list)
print(resume_links)


first_name
Agathe        [https://mayoclinic.com/nulla/mollis/molestie/...
Anna-diana    [http://bigcartel.com/mauris/morbi/non/lectus....
Arny          [http://ifeng.com/convallis.json?etiam=dolor&p...
Avivah        [https://webnode.com/enim/leo/rhoncus/sed.jsp?...
Basil         [https://home.pl/felis.jsp?sed=odio&ante=curab...
Bev           [http://washington.edu/erat.xml?vitae=lacinia&...
Conny         [https://ning.com/nullam/porttitor/lacus/at/tu...
Dall          [https://kickstarter.com/mattis/egestas.html?n...
Dionne        [http://wikia.com/aliquet/pulvinar/sed/nisl.js...
Druci         [https://ifeng.com/odio/curabitur/convallis/du...
Gertie        [http://cdc.gov/erat.png?integer=urna&ac=ut&ne...
Gibbie        [http://instagram.com/turpis/donec.jsp?dui=vol...
Giffy         [https://theglobeandmail.com/duis/bibendum.xml...
Godart        [http://mapy.cz/accumsan/odio/curabitur/conval...
Josefa        [https://berkeley.edu/non/mi/integer/ac/neque/...
Karry         [http://seattle

In [ ]:
from urllib.parse import urlparse
valid_url =[]
for i in resume_links:
    parsed_url = urlparse(i)
    if parsed_url.scheme=="https":
        valid_url.append(i)

['https://mayoclinic.com/nulla/mollis/molestie/lorem/quisque.png?duis=lectus&ac=aliquam&nibh=sit&fusce=amet&lacus=diam&purus=in&aliquet=magna&at=bibendum&feugiat=imperdiet&non=nullam&pretium=orci&quis=pede&lectus=venenatis&suspendisse=non&potenti=sodales&in=sed&eleifend=tincidunt&quam=eu&a=felis&odio=fusce&in=posuere&hac=felis&habitasse=sed&platea=lacus&dictumst=morbi&maecenas=sem&ut=mauris&massa=laoreet&quis=ut&augue=rhoncus']
['http://bigcartel.com/mauris/morbi/non/lectus.jpg?scelerisque=et&mauris=commodo&sit=vulputate&amet=justo&eros=in&suspendisse=blandit&accumsan=ultrices&tortor=enim&quis=lorem&turpis=ipsum&sed=dolor&ante=sit&vivamus=amet&tortor=consectetuer&duis=adipiscing&mattis=elit&egestas=proin&metus=interdum&aenean=mauris&fermentum=non&donec=ligula&ut=pellentesque&mauris=ultrices&eget=phasellus&massa=id&tempor=sapien&convallis=in&nulla=sapien&neque=iaculis&libero=congue&convallis=vivamus&eget=metus&eleifend=arcu&luctus=adipiscing&ultricies=molestie&eu=hendrerit&nibh=at&quisq

In [ ]:

# %pip install requests


In [73]:
import requests