In [1]:
import numpy as np

In [2]:
my_list= [1,2,3,4,5]
arr= np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
my_list1=[2,5,6,8,6]
my_list2=[7,4,3,5,2]
my_list3=[3,4,2,1,7]
my_list4=[6,7,3,2,1]
arr=np.array([my_list1,my_list2,my_list3,my_list4])

In [6]:
print(arr)

[[2 5 6 8 6]
 [7 4 3 5 2]
 [3 4 2 1 7]
 [6 7 3 2 1]]


In [7]:
arr.shape

(4, 5)

In [8]:
arr.reshape(2,10)

array([[2, 5, 6, 8, 6, 7, 4, 3, 5, 2],
       [3, 4, 2, 1, 7, 6, 7, 3, 2, 1]])

In [9]:
#Indexing
#accesing the array element
arr1= np.array ([1,5,3,7,9,2,2,6])

In [10]:
arr1[2]

np.int64(3)

In [11]:
arr
#arr[0:2,0:]

array([[2, 5, 6, 8, 6],
       [7, 4, 3, 5, 2],
       [3, 4, 2, 1, 7],
       [6, 7, 3, 2, 1]])

In [12]:
arr[1,1:4]

array([4, 3, 5])

In [13]:
#we can give a range and form a array
#when we take 2 steps one gap is taken
#one no. less than 10 is taken
arr1=np.arange(0,10,step=2)
print(arr1)
type(arr1)

[0 2 4 6 8]


numpy.ndarray

In [14]:
#
np.linspace(1,7,num=5)

array([1. , 2.5, 4. , 5.5, 7. ])

In [15]:
#copy
#changes every element after 2nd element
arr1[3:]=150
arr1

array([  0,   2,   4, 150, 150])

In [16]:
# changes in arr2 change in arr1
# arr2=arr1
# arr1[2:]=500
# print(arr2)

In [17]:
#refrence type 
arr1

array([  0,   2,   4, 150, 150])

In [18]:
#this a value type
arr2=arr1.copy()
arr2[3:]=20
print(arr1)
arr2

[  0   2   4 150 150]


array([ 0,  2,  4, 20, 20])

In [19]:
#some conditions for exploratory data analysis 
val=2
arr1[arr1<3000]#this is a bollean mask where inside the bracket returns bollean list

array([  0,   2,   4, 150, 150])

In [20]:
arr1*arr

array([[   0,   10,   24, 1200,  900],
       [   0,    8,   12,  750,  300],
       [   0,    8,    8,  150, 1050],
       [   0,   14,   12,  300,  150]])

In [21]:
#creats an arraywhere all the elements are replaced by ones
np.ones(4,dtype=int)#dtype means data type of one by default it is float

array([1, 1, 1, 1])

In [22]:
#default dtype is float
np.ones((2,3))#TWO DIMENSIONAL AARAY

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.random.rand(5,2)#uniform distribution it selects only 0 to 1 numbers randomly

array([[0.90417574, 0.84588115],
       [0.74454289, 0.83960638],
       [0.50956632, 0.2028009 ],
       [0.64342363, 0.09897561],
       [0.36129593, 0.51999875]])

In [24]:
np.random.randn(2,2)#numbers are selected randomly from standard normal distribuition

array([[ 0.80636498, -0.09074398],
       [-0.05524394, -0.34744255]])

In [25]:
np.random.randint(0,100,16).reshape(2,8)#as there are 16 elemnts in our array

array([[14, 12, 16, 28, 50, 50, 90, 72],
       [18, 44, 20, 26, 42, 90, 21, 74]], dtype=int32)

In [26]:
np.random.random_sample((1,5))#this has continuos distribuition every number as a equal chance between 0.0 to 1.0

array([[0.66993144, 0.49219752, 0.33515881, 0.43866025, 0.4039513 ]])